export const breadcrumbNameMap = {
    "profile": "Thông tin cá nhân",
    "accounts": "Quản lý tài khoản",
    "partners": "Quản lý đối tác",
    "tech": "Ban Chuyên môn",
    "event": "Ban Sự kiện",
    "hr": "Ban Nhân sự - Tổ chức",
    "fer": "Ban Tài chính - Đối ngoại",
    "pr": "Ban Truyền thông",
    "homepage-achievements": "Thành tựu",
    "homepage-partners": "Đối tác",
    "homepage-faqs": "FAQs",
    "homepage-banners": "Quản lý Banner",
    "faqs": "Quản lý FAQs",
    "et-news": "Quản lý ET News",
    "et-blog": "Quản lý ET Blog",
    "activities": "Quản lý Hoạt động",
    "collaborator": "Quản lý Tìm kiếm CTV",
    "overview": "Tổng quan",
    "approve": "Phê duyệt",
    "archive": "Lưu trữ",
    "create": "Thêm mới",
};